const loadNotes = async () => {
    const loadedNotes={
      "0-a": await PianoNotes.A0(),
      "0-as": await PianoNotes.ASharp0(),
      "0-b": await PianoNotes.B0(),
      "1-c": await PianoNotes.C1(),
      "1-cs": await PianoNotes.CSharp1(),
      "1-d": await PianoNotes.D1(),
      "1-ds": await PianoNotes.DSharp1(),
      "1-e": await PianoNotes.E1(),
      "1-f": await PianoNotes.F1(),
      "1-fs": await PianoNotes.FSharp1(),
      "1-g": await PianoNotes.G1(),
      "1-gs": await PianoNotes.GSharp1(),
      "1-a": await PianoNotes.A1(),
      "1-as": await PianoNotes.ASharp1(),
      "1-b": await PianoNotes.B1(),
      "2-c": await PianoNotes.C2(),
      "2-cs": await PianoNotes.CSharp2(),
      "2-d": await PianoNotes.D2(),
      "2-ds": await PianoNotes.DSharp2(),
      "2-e": await PianoNotes.E2(),
      "2-f": await PianoNotes.F2(),
      "2-fs": await PianoNotes.FSharp2(),
      "2-g": await PianoNotes.G2(),
      "2-gs": await PianoNotes.GSharp2(),
      "2-a": await PianoNotes.A2(),
      "2-as": await PianoNotes.ASharp2(),
      "2-b": await PianoNotes.B2(),
      "3-c": await PianoNotes.C3(),
      "3-cs": await PianoNotes.CSharp3(),
      "3-d": await PianoNotes.D3(),
      "3-ds": await PianoNotes.DSharp3(),
      "3-e": await PianoNotes.E3(),
      "3-f": await PianoNotes.F3(),
      "3-fs": await PianoNotes.FSharp3(),
      "3-g": await PianoNotes.G3(),
      "3-gs": await PianoNotes.GSharp3(),
      "3-a": await PianoNotes.A3(),
      "3-as": await PianoNotes.ASharp3(),
      "3-b": await PianoNotes.B3(),
      "4-c": await PianoNotes.C4(),
      "4-cs": await PianoNotes.CSharp4(),
      "4-d": await PianoNotes.D4(),
      "4-ds": await PianoNotes.DSharp4(),
      "4-e": await PianoNotes.E4(),
      "4-f": await PianoNotes.F4(),
      "4-fs": await PianoNotes.FSharp4(),
      "4-g": await PianoNotes.G4(),
      "4-gs": await PianoNotes.GSharp4(),
      "4-a": await PianoNotes.A4(),
      "4-as": await PianoNotes.ASharp4(),
      "4-b": await PianoNotes.B4(),
      "5-c": await PianoNotes.C5(),
      "5-cs": await PianoNotes.CSharp5(),
      "5-d": await PianoNotes.D5(),
      "5-ds": await PianoNotes.DSharp5(),
      "5-e": await PianoNotes.E5(),
      "5-f": await PianoNotes.F5(),
      "5-fs": await PianoNotes.FSharp5(),
      "5-g": await PianoNotes.G5(),
      "5-gs": await PianoNotes.GSharp5(),
      "5-a": await PianoNotes.A5(),
      "5-as": await PianoNotes.ASharp5(),
      "5-b": await PianoNotes.B5(),
      "6-c": await PianoNotes.C6(),
      "6-cs": await PianoNotes.CSharp6(),
      "6-d": await PianoNotes.D6(),
      "6-ds": await PianoNotes.DSharp6(),
      "6-e": await PianoNotes.E6(),
      "6-f": await PianoNotes.F6(),
      "6-fs": await PianoNotes.FSharp6(),
      "6-g": await PianoNotes.G6(),
      "6-gs": await PianoNotes.GSharp6(),
      "6-a": await PianoNotes.A6(),
      "6-as": await PianoNotes.ASharp6(),
      "6-b": await PianoNotes.B6(),
      "7-c": await PianoNotes.C7(),
      "7-cs": await PianoNotes.CSharp7(),
      "7-d": await PianoNotes.D7(),
      "7-ds": await PianoNotes.DSharp7(),
      "7-e": await PianoNotes.E7(),
      "7-f": await PianoNotes.F7(),
      "7-fs": await PianoNotes.FSharp7(),
      "7-g": await PianoNotes.G7(),
      "7-gs": await PianoNotes.GSharp7(),
      "7-a": await PianoNotes.A7(),
      "7-as": await PianoNotes.ASharp7(),
      "7-b": await PianoNotes.B7(),
      "8-c": await PianoNotes.C8(),
    }
    
    console.log(loadedNotes);

    setNotes(loadedNotes);
  };

  loadNotes();